spring:
  cloud:
    function:
      definition: produceLead,salesChannelResult
      stream:
        binders:
          kafka-optimus:
            type: kafka
            environment.spring.cloud.stream.kafka.binder:
              brokers: 10.0.81.59:9092
          kafka-atlas:
            type: kafka
            environment.spring.cloud.stream.kafka.binder:
              brokers: globalsearch_kafka_zookeeper01.kapitalbank.az:9092,globalsearch_kafka_zookeeper02.kapitalbank.az:9092,globalsearch_kafka_zookeeper03.kapitalbank.az:9092
        bindings:
          checkFraud-out-0:
            binder: kafka-optimus
            contentType: application/json
            group: loan-lead-group
            destination: hot-lead-integration-loan
          checkFraudResult-in-0:
            binder: kafka-atlas
            contentType: application/json
            group: sale-channel-online-state
            destination: sale-channel-8196
  datasource:
    url: jdbc:oracle:thin:@//172.21.14.34:1521/ldb
    username: LEAD_HOT
    password: 4H68enVKjpr##ApzemCG4Y
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8083

loan:
  sql:
    sources: "0008"